# Generated by Django 4.2.7 on 2024-05-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Nurture", "0003_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.BooleanField(null=True),
        ),
    ]
